apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: angular-app
          image: caiquelacerda15/front-end-hendrixbot:dev-latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
